# Generated by Django 4.0 on 2021-12-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser__3bse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_3bse',
        ),
    ]
