# Generated by Django 4.0 on 2021-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser__3bse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
